
import torch
import torch.nn as nn
import torch.quantization
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import os
from PIL import Image
import shutil
import numpy as np

# --- 1. Model Definition (must match training) ---
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=2):
        super(SimpleCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 62 * 62, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

def main():
    # Data paths (assuming augmented data is already generated by train.py or a similar process)
    base_augmentation_output_folder = '/content/augmented_outputImg'
    model_path = 'simple_cnn_model.pth'
    quantized_model_save_path = 'quantized_simple_cnn_model.pth'

    # Check if the trained model exists
    if not os.path.exists(model_path):
        print(f"Error: Trained model '{model_path}' not found. Please run train.py first.")
        return

    # Check if augmented data exists for calibration
    if not os.path.exists(base_augmentation_output_folder) or not os.listdir(base_augmentation_output_folder):
        print(f"Warning: Augmented data folder '{base_augmentation_output_folder}' is empty or does not exist. Calibration will likely fail.")
        print("Please ensure data augmentation has been performed (e.g., by running train.py).")

    # Transformations for the dataset (for calibration)
    dataset_transforms = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Load the full dataset (needed for class count and calibration data)
    full_dataset = datasets.ImageFolder(root=base_augmentation_output_folder, transform=dataset_transforms)

    # Instantiate the original model and load its weights
    original_model = SimpleCNN(num_classes=len(full_dataset.classes))
    original_model.load_state_dict(torch.load(model_path))
    original_model.to('cpu') # Quantization usually happens on CPU
    original_model.eval() # Set to evaluation mode

    print("Original model loaded.")

    # 1. Define Quantization Configuration
    qconfig = torch.quantization.get_default_qconfig('fbgemm')

    # Fuse modules: Merge Conv-ReLU for better quantization performance.
    fused_model = torch.quantization.fuse_modules(original_model, [['features.0', 'features.1'], ['features.3', 'features.4']])
    fused_model.qconfig = qconfig

    # 2. Prepare the model for static quantization
    quantized_model_prepared = torch.quantization.prepare(fused_model, inplace=False)
    print("Model prepared for quantization.")

    # 3. Calibrate the model
    # Use a small subset of the dataset for calibration
    # Splitting for calibration data:
    calibration_size = int(0.1 * len(full_dataset)) # Use 10% of data for calibration
    _ , calibration_dataset = torch.utils.data.random_split(full_dataset, [len(full_dataset) - calibration_size, calibration_size])

    calibration_loader = DataLoader(calibration_dataset, batch_size=32, shuffle=False, num_workers=0)
    print("Starting model calibration...")

    with torch.no_grad():
        for i, (inputs, labels) in enumerate(calibration_loader):
            if i >= 5: # Calibrate with 5 batches
                break
            inputs = inputs.to('cpu')
            quantized_model_prepared(inputs)
    print("Model calibration complete.")

    # 4. Convert the model to a quantized version
    quantized_model = torch.quantization.convert(quantized_model_prepared, inplace=False)

    # 5. Save the quantized model
    torch.save(quantized_model.state_dict(), quantized_model_save_path)
    print(f"Quantized model saved to {quantized_model_save_path}")

    # Compare model sizes
    def print_model_size(model_path, name):
        size_bytes = os.path.getsize(model_path)
        size_mb = size_bytes / (1024 * 1024)
        print(f"Size of {name}: {size_mb:.2f} MB")

    print("
--- Model Size Comparison ---")
    print_model_size(model_path, 'Original Model')
    print_model_size(quantized_model_save_path, 'Quantized Model')

    print("Quantization process finished.")

if __name__ == '__main__':
    main()
